In [37]:
import numpy as np
import sklearn
import sklearn.preprocessing

In [38]:
arr = np.array([[5.1, -2.9, 3.3], [ -1.2, 7.8, -6.1], [3.9, 0.4, 2.1], [7.3, -9.9, -4.5]])

In [39]:
arr.mean()

0.4416666666666666

In [40]:
arr.std()

5.274065214698135

In [41]:
arr

array([[ 5.1, -2.9,  3.3],
       [-1.2,  7.8, -6.1],
       [ 3.9,  0.4,  2.1],
       [ 7.3, -9.9, -4.5]])

In [42]:
binarized_scaler = sklearn.preprocessing.Binarizer(threshold=2.0)


In [43]:
binarized_arr = binarized_scaler.transform(arr)

In [44]:
binarized_arr

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.],
       [1., 0., 0.]])

In [47]:
scaled_arr = sklearn.preprocessing.scale(arr, axis=0,with_mean=True, with_std=True)

In [48]:
scaled_arr

array([[ 0.42462551, -0.2748757 ,  1.13244172],
       [-1.59434861,  1.40579288, -1.18167831],
       [ 0.04005901,  0.24346134,  0.83702214],
       [ 1.12966409, -1.37437851, -0.78778554]])